In [1]:
import sys
sys.path.append("..")

import pandas as pd
import numpy as np

from src.data.data_cleaning import load_config, project_path
from src.features.build_features import build_features, load_interim, add_calendar_features, add_lag_features, add_rolling_features

In [2]:
config = load_config("config/config.yaml")

In [3]:
df_interim = load_interim(config)
df_interim.head()

        date  sales  promo  is_holiday
0 2023-01-01  380.2      0           1
1 2023-01-02  236.7      0           0
2 2023-01-03  232.4      0           0
3 2023-01-04  235.2      0           0
4 2023-01-05  345.8      1           0

In [5]:
df_processed = build_features(config)
print(df_processed.shape)
df_processed.columns.to_list()

(1065, 17)

['date',
 'sales',
 'promo',
 'is_holiday',
 'day_of_week',
 'is_weekend',
 'month',
 'day_of_year',
 'week_of_year',
 'sales_lag_1',
 'sales_lag_7',
 'sales_lag_14',
 'sales_lag_30',
 'sales_rolling_mean7',
 'sales_rolling_std7',
 'sales_rolling_mean30',
 'sales_rolling_std30']

In [7]:
df_processed.isna().sum().sum()

np.int64(0)

In [8]:
df_processed[["date", "sales", "sales_lag_1", "sales_lag_7"]].head(10)
# sales_lag_1 baris ke-N harus = sales baris ke-(N-1)
# sales_lag_7 baris ke-N harus = sales 7 baris sebelumnya

        date  sales  sales_lag_1  sales_lag_7
0 2023-01-31  246.7        245.2        217.7
1 2023-02-01  245.6        246.7        273.2
2 2023-02-02  266.1        245.6        237.4
3 2023-02-03  250.2        266.1        235.8
4 2023-02-04  279.5        250.2        285.3
5 2023-02-05  274.5        279.5        293.8
6 2023-02-06  251.1        274.5        245.2
7 2023-02-07  222.1        251.1        246.7
8 2023-02-08  231.6        222.1        245.6
9 2023-02-09  223.4        231.6        266.1

In [9]:
df_processed.drop(columns=["date"]).corr()["sales"].sort_values(ascending=False)

sales                   1.000000
sales_rolling_mean7     0.866887
sales_rolling_mean30    0.865990
sales_lag_7             0.838030
sales_lag_14            0.820505
sales_lag_1             0.794779
sales_lag_30            0.712655
promo                   0.300006
is_weekend              0.254056
day_of_week             0.202428
day_of_year             0.198978
month                   0.197117
week_of_year            0.182875
is_holiday              0.113140
sales_rolling_std7     -0.008640
sales_rolling_std30    -0.022335
Name: sales, dtype: float64